### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by praveenkumartapmobi** [douban/DOUAudioStreamer#53]
Hello Douban,

After, following your instructions to add the source files `src` into my application, i am getting below error,

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_DOUMPMediaLibraryAssetLoader", referenced from:
      objc-class-ref in DOUAudioFileProvider.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

IDE : XCode 6.0
SDK : iOS 8.0

Researched lot about this. No solution yet. Do i need to import any frameworks or libs for this?

**Comment by lembacon** [comment]
You have to configure your project settings to link against the `MediaPlayer.framework`.

**Comment by AndreasKlein** [comment]
I can second @h1101723183's solution, adding the `MediaPlayer.framework` along didn't do it.

**Comment by vatsal1992** [comment]
@h1101723183  , hi, your solution worked on swift3.0 project. you just saved me.. thanks 👍

**Comment by h1101723183** [comment]
@vatsal1992 I'm glad to help you!
